---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

# page title
title: IoT Gateway Homepage

# ui language
language: en

# default layout
layout:
  IoT Gateway Core:
  Services:
  Applications:

providers:
  openweathermap: apikey
  weatherapi: weatherapiapikey
