version: "3"

services:

  nodered:
    image: nodered/node-red
    restart: always
    ports:
    - 1880:1880
    volumes:
    - nodered_data:/data
    labels:
      # homepage setup
      homepage.group: Services
      homepage.name: Node-RED
      homepage.icon: node-red.png
      homepage.href: http://${HOSTIP:-localhost}/nodered/
      homepage.description: Node-RED

      # traefik setup
      traefik.enable: true
      traefik.http.services.nodered.loadbalancer.server.port: 1880

      # middleware
      traefik.http.middlewares.nodered-rewrite.replacepathregex.regex: "^/nodered/(.*)"
      traefik.http.middlewares.nodered-rewrite.replacepathregex.replacement: "/$$1"

      # routers
      traefik.http.routers.nodered.entrypoints: web
      traefik.http.routers.nodered.rule: PathPrefix(`/nodered/`)
      traefik.http.routers.nodered.middlewares: "nodered-rewrite"
    networks:
      - iotgw


  zigbee2mqtt:
    restart: always
    image: koenkk/zigbee2mqtt
    volumes:
      - ./configs/zigbee2mqtt/configuration.yaml:/app/data/configuration.yaml
      - zigbee2mqtt_data:/app/data/
      - /run/udev:/run/udev:ro
    # ports:
      # - 8000:8080
    environment:
      - TZ=Europe/Bratislava
    devices:
      - ${IOTGW_ZIGBEE_ADAPTER:-/dev/ttyUSB1}:/dev/ttyUSB1
    labels:
      # homepage setup
      homepage.group: Services
      homepage.name: Zigbee2MQTT
      homepage.icon: zigbee2mqtt.png
      homepage.href: http://${HOSTIP:-localhost}/zigbee2mqtt/
      homepage.description: Zigbee to MQTT bridge

      # traefik setup
      traefik.enable: true
      traefik.http.services.zigbee2mqtt.loadbalancer.server.port: 8080

      # middleware
      traefik.http.middlewares.zb2mqtt-rewrite.replacepathregex.regex: "^/zigbee2mqtt/(.*)"
      traefik.http.middlewares.zb2mqtt-rewrite.replacepathregex.replacement: "/$$1"

      # routers
      traefik.http.routers.zigbee2mqtt.entrypoints: web
      traefik.http.routers.zigbee2mqtt.rule: PathPrefix(`/zigbee2mqtt/`)
      traefik.http.routers.zigbee2mqtt.middlewares: "zb2mqtt-rewrite"
    networks:
      - iotgw

volumes:
  nodered_data:
  zigbee2mqtt_data:

networks:
  iotgw:
    external: true

